const StatePlace=[
    {
        index_no:1,
        place:"Kolkata",
        name:"Victoria Memorial",
        pic:"https://www.fabhotels.com/blog/wp-content/uploads/2019/02/Victoria-Memorial-Sound-and-Light-Show.jpg",
        details:"An imposing white monument, Victoria Memorial is one of the most visited places in Kolkata, and for all good reasons. Named after Queen Victoria, it now serves as a museum and is perfect for history buffs. If you ever feel like taking a walk down our past and reflect on how long India has come from its colonization days, visit this place. There are light and sound shows held in the evening. The era of India’s freedom struggle is shown not only through the light and sound show but through a series of paintings, artifacts, sculptures and books. We would recommend spending at least 3-4 hours to gain knowledge about our country’s past.",
        price:"INR 30 for Indians, and INR 200 for foreigners",
        timing:"10:00 a.m. to 5:00 p.m.",
        location:"Victoria Memorial Hall, 1, Queen's Way, Kolkata",
    },
    {
        index_no:2,
        place:"Kolkata",
        name:"Indian Museum, Kolkata",
        pic:"https://www.transindiatravels.com/wp-content/uploads/indian-museum.jpg",
        details:"Witness the charm of the glorious country of India the oldest, and the largest museum in India, the Indian Museum. It is one of the best places to visit in Kolkata for youngsters where they can gain insights into the rich tradition and cultural heritage of their country.",
        price:"INR 20 for Indians, and INR 500 for foreigners",
        timing:"10:00 am to 5:00 pm",
        location:" 27, Jawaharlal Nehru Rd, Colootola, New Market Area, Dharmatala, Taltala, Kolkata",
    },
    {
        index_no:3,
        place:"Kolkata",
        name:"Dakshineswar Kali Temple, Kolkata",
        pic:"https://www.trawell.in/admin/images/upload/555418100Kolkata_Dakshineswar_Kali_Temple_Main.jpg",
        details:"Located in the Dakshineswar town of Kolkata, the Dakshineswar Kali Temple is a popular pilgrimage site dedicated to Goddess Kali. It is one of the must-visit places to visit in Kolkata in one day as one cannot afford to miss out on this architectural masterpiece which is also considered one of the holiest places in the city. It is also surrounded by some of the best cafes in Kolkata.",
        price:"Free",
        timing:"6:00 am to 12:30 pm and3:00 pm to 8:30 pm",
        location:" Dakshineswar, Kolkata",
    },
    {
        index_no:4,
        place:"Kolkata",
        name:"M.P. Birla Planetarium, Kolkata",
        pic:"https://assets-news.housing.com/news/wp-content/uploads/2022/07/11000910/Kolkata-4.jpg",
        details:"In the list of places to visit in Kolkata, one cannot ignore the majestic Birla Planetarium. Inaugurated in 1963 by Pandit Jawaharlal Nehru, the planetarium has exhibition corners, several galleries, a library, and a very impressive theatre room with high-end projector screens. It is a great place to introduce astronomy to children",
        price:"₹100 per head",
        timing:"12:30 PM to 6:30 PM",
        location:"Jawaharlal Nehru Road, Kolkata",
    },
    {
        index_no:5,
        place:"Kolkata",
        name:"Princep Ghat, Kolkata",
        pic:"https://hikerwolf.com/wp-content/uploads/2020/04/Hooghly-shutterstock-1067x800.jpg",
        details:"Located along the river Hooghly, Princep Ghat is a perfect place to spend your evenings. The surroundings are fully lit up post-sunset and you can pack some food and spend a relaxed time enjoying the grounds. The Princep Ghat is a Greek-style building located in a strategic place right under the 2nd Hooghly Bridge.",
        price:"Free",
        timing:"8:00 am to 8:00 pm Best time to visit  After 6:00 PM",
        location:"Fort William, Hastings, Kolkata",
    },
    {
        index_no:6,
        place:"Kolkata",
        name:"Alipore Zoo, Kolkata",
        pic:"https://www.holidify.com/images/cmsuploads/compressed/20170310204136_20171030202918.jpg",
        details:"The Alipore Zoo is one of the major tourist attractions in Kolkata, especially if you are travelling with children. The zoo is the oldest in the country and houses amazing species of animals, birds, and reptiles. You can spot the one-horned rhinoceros, white tigers, zebras, the Swinhoe’s Pheasant, and many migratory birds here.",
        price:"INR 25 (adults) | INR 10 (kids below 5)",
        timing:"9:00 am to 5:00 pm (closed on Thursday)",
        location:" Belvedere Road, Lake Place, Alipore, Kolkata 700025",
    },
    {
        index_no:7,
        place:"Kolkata",
        name:"New Town Eco Park, Kolkata",
        pic:"https://www.fabhotels.com/blog/wp-content/uploads/2021/09/28-New-Town-Eco-Park.jpg",
        details:"Ecotourism park is an enormous urban park that is considered the best among the incredible places to visit in Kolkata. This biggest urban park in India is spread over 475 acres and is considered as a perfect retreat for nature admirers. The park features three major parts, that’s the ecological zones, the gardens, and the recreational zones. There are numerous activities that can be attended on the basis of the preference of the visitors. The cottages and conference halls inside the Eco-tourism park can be rented for personal or business needs.",
        price:"50 per head entry fee",
        timing:"2.30 pm to 8.30 pm (Monday closed)",
        location:"Major Arterial Road(South-East), AA II, Newtown, Kolkata",
    },
    {
        index_no:8,
        place:"Kolkata",
        name:"ISKCON Temple, Kolkata",
        pic:"https://travelikan.com/wp-content/uploads/2023/06/ISKCON-Headquarters-Mayapur.jpg",
        details:"ISKCON Kolkata is the first ISKCON centre in the country, established in 1972 by A.C. Bhaktivedanta Swami Prabhupada. Also referred as Sri Sri Radha Govind Mandir, the organisation popularises the teachings of Lord Krishna based on the sacred Bhagwad Geeta and Vedas. When here, do savour the 100% Satvik meal prepared by volunteer devotees.",
        price:"Free",
        timing:"4:30 am to 1:00 pm and 4:00 pm to 8:30 pm",
        location:"Mayapur",
    },
    {
        index_no:9,
        place:"Kolkata",
        name:"Howrah Bridge, Kolkata",
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcJLLO5tXdtB-_-Aoux1jJPqualHHjeN32GjEcAfyfZ4S27VtKUz0jwzNVJlNFmDj_lAY&usqp=CAU",
        details:"To say that Howrah Bridge is one of the top places to visit in Kolkata would be an understatement. An unofficial emblem of the city, Howrah Bridge merits a visit if you want to spend some time alone with just the ocean in front of you. Sit here in silence or simply observe the fishermen go about their work at dawn and dusk.",
        price:"Free",
        timing:'Any Time',
        location:"Near Howrah Station the bridge has been renamed after Rabindranath Tagore and is now called Rabindra Setu.",
    },
   
];
module.exports=StatePlace;


// {
//     place:,
//     name:,
//     pic:,
//     details:,
//     price:,
//     timing:,
//     location:,
// },
// {
//     place:,
//     name:,
//     pic:,
//     details:,
//     price:,
//     timing:,
//     location:,
// },
// {
//     place:,
//     name:,
//     pic:,
//     details:,
//     price:,
//     timing:,
//     location:,
// },
// {
//     place:,
//     name:,
//     pic:,
//     details:,
//     price:,
//     timing:,
//     location:,
// },
// {
//     place:,
//     name:,
//     pic:,
//     details:,
//     price:,
//     timing:,
//     location:,
// },
// {
//     place:,
//     name:,
//     pic:,
//     details:,
//     price:,
//     timing:,
//     location:,
// }