const traindata=[{
    train_number: "12810",
    train_name: "HOWRAH - MUMBAI CSMT SF Mail",
    train_src: "HWH",
    train_dstn: "CSMT",
    arrival_time:"7:50PM",
    dest_time:"04:25AM",
    from_station_name:"HOWRAH JN",
    to_station_name:"MUMBAI CSMT",
    duration:"1d8hr35min",
    source:"Howrah",
    destination:"Mumbai",
},
{
    train_number: "12860",
    train_name: "HOWRAH - MUMBAI CSMT Gitanjali SF Express",
    train_src: "HWH",
    train_dstn: "CSMT",
    arrival_time:"2:50PM",
    dest_time:"9:20PM",
    from_station_name:"HOWRAH JN",
    to_station_name:"MUMBAI CSMT",
    duration:"1d7hr15min",
    source:"Howrah",
    destination:"Mumbai",
},
    {
    train_number: "12810",
    train_name: "HOWRAH - MUMBAI CSMT SF Mail",
    train_src: "HWH",
    train_dstn: "CSMT",
    arrival_time:"7:50PM",
    dest_time:"04:25AM",
    from_station_name:"HOWRAH JN",
    to_station_name:"MUMBAI CSMT",
    duration:"1d8hr35min",
    source:"Howrah",
    destination:"Mumbai",
},
    {
        train_number: "18030",
        train_name: "SHALIMAR - MUMBAI LTT Express",
        train_src: "SHM",
        train_dstn: "LTT",
        arrival_time:"3.35PM",
        dest_time:"04:05AM",
        from_station_name:"HOWRAH JN",
        to_station_name:"MUMBAI CSMT",
        duration:"1d8hr35min",
        source:"Howrah",
        destination:"Mumbai",
    },
        {
            train_number: "12810",
            train_name: "HOWRAH - MUMBAI CSMT SF Mail",
            train_src: "HWH",
            train_dstn: "CSMT",
            arrival_time:"7:50PM",
            dest_time:"04:25AM",
            from_station_name:"KOLKATA SHALIMAR",
            to_station_name:"LOKMANYA TILAK TERM",
            duration:"1d12hr30min",
            source:"Howrah",
            destination:"Mumbai",
        },
            
];
module.exports=traindata;